# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
pipelines:
  branches:
    master:
      - step:
          script:
            - git push git@git.wpengine.com:production/tmentertain.git master
            - echo "Completed"
    staging:
      - step:
          script:
            - git push git@git.wpengine.com:production/tmestaging.git staging
            - echo "Completed"
